<?php

namespace app\models;

use Ramsey\Uuid\Uuid;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "posts".
 *
 * @property string $id
 * @property string $title
 * @property string $slug
 * @property string $body
 * @property string $created_by
 * @property int $created_at
 *
 * @property User $createdBy
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * {@inheritDoc}
     */
    public static function tableName(): string
    {
        return 'posts';
    }
    
    /**
     * {@inheritDoc}
     */
    public function behaviors(): array
    {
        return [
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title'
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => false,
            ],
        ];
    }
    
    /**
     * {@inheritDoc}
     */
    public function rules(): array
    {
        return [
            [['title', 'body'], 'required'],
            [['body'], 'string'],
            [['created_at'], 'integer'],
            [['id', 'created_by'], 'string', 'max' => 36],
            [['title'], 'string', 'max' => 64],
            [['title'], 'unique'],
            [['id'], 'unique'],
            [
                ['created_by'],
                'exist',
                'skipOnError' => true,
                'targetClass' => User::class,
                'targetAttribute' => ['created_by' => 'id']
            ],
        ];
    }
    
    /**
     * {@inheritDoc}
     */
    public function fields(): array
    {
        $fields = parent::fields();
        $fields['created_at'] = function($model) {
            return (new \DateTime())->setTimestamp($this->created_at)->format('Y-m-d H:i:s');
        };
        return $fields;
    }
    
    /**
     * Gets query for [[CreatedBy]].
     *
     * @return ActiveQuery
     */
    public function getCreatedBy(): ActiveQuery
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }
    
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->id = Uuid::uuid4()->toString();
                $this->created_at = (new \DateTime('now'))->getTimestamp();
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
